# Generated by Django 5.0.3 on 2024-04-02 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('store', '0002_shoppingcart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shoe',
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shoe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.shoe')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='orderitem',
            field=models.ManyToManyField(to='orders.orderitem'),
        ),
    ]
