# Generated by Django 5.0.3 on 2024-04-08 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_shoe_order_total_orderitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderitem',
            new_name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='shippinginfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.shippinginfo'),
        ),
    ]
