# Generated by Django 5.0.3 on 2024-03-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_shoe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
