# Generated by Django 5.0.3 on 2024-03-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_shoe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
