# Generated by Django 5.0.3 on 2024-03-28 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_shoe_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='approved',
            new_name='is_approved',
        ),
    ]
