# Generated by Django 5.0.3 on 2024-03-17 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_shoe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shoe',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_parent',
            new_name='parent',
        ),
    ]
