# Generated by Django 5.0.3 on 2024-03-17 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_shoe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shoe',
        ),
    ]
