# Generated by Django 5.0.3 on 2024-04-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_subtotal_cartitem_item_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='cart_items',
            field=models.ManyToManyField(to='store.cartitem'),
        ),
    ]
