# Generated by Django 5.0.3 on 2024-04-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_shoppingcart_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='cart_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
