# Generated by Django 5.0.3 on 2024-04-03 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentinfo',
            old_name='card_holder',
            new_name='cardholder',
        ),
        migrations.RenameField(
            model_name='paymentinfo',
            old_name='card_cvv',
            new_name='cardnumber',
        ),
        migrations.RenameField(
            model_name='paymentinfo',
            old_name='card_number',
            new_name='cvv',
        ),
        migrations.RenameField(
            model_name='paymentinfo',
            old_name='card_expiration',
            new_name='expiration',
        ),
    ]
