# Generated by Django 5.0.3 on 2024-04-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_card_holder_paymentinfo_cardholder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='cardnumber',
            field=models.CharField(blank=True, null=True),
        ),
    ]
