# Generated by Django 5.0.3 on 2024-04-20 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentinfo_cardnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='balance',
        ),
    ]
