# Generated by Django 5.0.3 on 2024-03-18 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_buyer', models.BooleanField(default=True)),
                ('is_seller', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this customer belongs to. A customer will get all permissions granted to each of their groups', related_name='customer_set', to='auth.group', verbose_name='groups')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this customer', related_name='customer_set', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.CharField(blank=True, null=True)),
                ('card_number', models.BinaryField(blank=True, null=True)),
                ('card_expiration', models.BinaryField(blank=True, null=True)),
                ('card_cvv', models.BinaryField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_infos', to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.BinaryField(blank=True, null=True)),
                ('city', models.BinaryField(blank=True, null=True)),
                ('zipcode', models.BinaryField(blank=True, null=True)),
                ('state', models.BinaryField(blank=True, null=True)),
                ('country', models.BinaryField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_infos', to='accounts.customer')),
            ],
        ),
    ]
