# Generated by Django 5.0.3 on 2024-04-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_paymentinfo_shippinginfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippinginfo',
            name='customer',
        ),
        migrations.DeleteModel(
            name='PaymentInfo',
        ),
        migrations.DeleteModel(
            name='ShippingInfo',
        ),
    ]
