# Generated by Django 5.0.3 on 2024-03-21 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_paymentinfo_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippinginfo',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='product_id',
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_buyer', models.BooleanField(default=True)),
                ('is_seller', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='PaymentInfo',
        ),
        migrations.DeleteModel(
            name='ShippingInfo',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
