# Generated by Django 5.0.3 on 2024-03-17 01:04

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_buyer_paymentinfo_seller_shippinginfo_paymentmethods_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_buyer', models.BooleanField(default=True)),
                ('is_seller', models.BooleanField(default=True)),
                ('payment_methods', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.paymentmethods')),
                ('shipping_methods', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.shippingmethods')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
