# Generated by Django 5.0.3 on 2024-03-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customer_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethods',
            name='payment_info',
        ),
        migrations.RemoveField(
            model_name='shippingmethods',
            name='shipping_info',
        ),
        migrations.AddField(
            model_name='paymentmethods',
            name='payment_info',
            field=models.ManyToManyField(to='accounts.paymentinfo'),
        ),
        migrations.AddField(
            model_name='shippingmethods',
            name='shipping_info',
            field=models.ManyToManyField(to='accounts.shippinginfo'),
        ),
    ]
